

service: notes-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:PutItem
      Resource: !GetAtt notesTable.Arn




functions:
  createNote:
    handler: handler.createNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:PutItem
      Resource: !GetAtt notesTable.Arn  
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: handler.updateNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:UpdateItem
      Resource: !GetAtt notesTable.Arn  
    events:
      - http:
          method: put
          path: notes/{id}
  deleteNote:
    handler: handler.deleteNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:DeleteItem
      Resource: !GetAtt notesTable.Arn  
    events:
      - http:
          method: delete
          path: notes/{id}
  getAllNotes:
    handler: handler.getAllNotes
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamoDb:Scan
      Resource: !GetAtt notesTable.Arn  
    events:
      - http:
          method: get
          path: notes

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    notesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH