version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing serverless CLI
      - npm i -g serverless@2
      - echo Installing npm dependencies of note services
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      - serverless deploy --stage dev
artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'notes/node_module/**/*'
